set-option -sa terminal-overrides ",xterm*:Tc"
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

set -g set-clipboard on
if-shell 'command -v tmux-copy >/dev/null 2>&1' 'bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel "tmux-copy"'
if-shell 'command -v tmux-copy >/dev/null 2>&1' 'bind-key -T copy-mode-vi MouseDragEnd1Pane send -X copy-pipe-and-cancel "tmux-copy"'
